branch-defaults:
  default:
    environment: shipcoradmin-env
  master:
    environment: shipcoradmin-env
environment-defaults:
  shipcoradmin-env:
    branch: null
    repository: null
global:
  application_name: ShipCorAdmin
  branch: null
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2016.09 v3.3.1 running Node.js
  default_region: us-west-2
  profile: null
  repository: null
  sc: git
