// Generated by CoffeeScript 1.12.2
(function() {
  var Sequelize, User, config, pg, sequelize;

  pg = require('pg');

  config = require('../config');

  Sequelize = require('sequelize');

  sequelize = new Sequelize(config.DATABASE_URL);

  User = require('./user').define(sequelize);

  module.exports = {
    sequelize: sequelize,
    User: User,
    createTablesIfNotExist: function() {
      return User.sync();
    }
  };

}).call(this);
