// Generated by CoffeeScript 1.12.2
(function() {
  var Sequelize;

  Sequelize = require('sequelize');

  module.exports.define = function(sequelize) {
    return sequelize.define('user', {
      email: {
        type: Sequelize.STRING,
        allowNull: false,
        unique: true
      },
      hash: {
        type: Sequelize.STRING
      }
    });
  };

}).call(this);
