// Generated by CoffeeScript 1.12.2
(function() {
  module.exports = {
    MWS_SECRET_KEY: process.env.MWS_SECRET_KEY || void 0,
    MWS_AUTH_TOKEN: process.env.MWS_AUTH_TOKEN || void 0,
    SELLER_ID: process.env.SELLER_ID || void 0,
    AWS_ACCESS_KEY: process.env.AWS_ACCESS_KEY || void 0,
    DATABASE_URL: process.env.DATABASE_URL || 'postgres://postgres:admin@localhost:5432/shipcor'
  };

}).call(this);
