// Generated by CoffeeScript 1.12.2
(function() {
  var getlatestreports, requestreports;

  requestreports = require('./requestreports');

  getlatestreports = require('./getlatestreports');

  module.exports.requestReports = function() {
    return requestreports.requestReports();
  };

  module.exports.getLatestReports = function() {
    return getlatestreports.getReports();
  };

}).call(this);
